/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/vinicius/Dropbox/arv/projetos/mestradocomp/Dissertacao/mmaster_hydro/catkin_ws/src/ros_mmaster/srv/Srv.srv
 *
 */


#ifndef ROS_MMASTER_MESSAGE_SRV_H
#define ROS_MMASTER_MESSAGE_SRV_H

#include <ros/service_traits.h>


#include <ros_mmaster/SrvRequest.h>
#include <ros_mmaster/SrvResponse.h>


namespace ros_mmaster
{

struct Srv
{

typedef SrvRequest Request;
typedef SrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Srv
} // namespace ros_mmaster


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mmaster::Srv > {
  static const char* value()
  {
    return "713e5cf1444846805670f946f08bfc96";
  }

  static const char* value(const ::ros_mmaster::Srv&) { return value(); }
};

template<>
struct DataType< ::ros_mmaster::Srv > {
  static const char* value()
  {
    return "ros_mmaster/Srv";
  }

  static const char* value(const ::ros_mmaster::Srv&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mmaster::SrvRequest> should match 
// service_traits::MD5Sum< ::ros_mmaster::Srv > 
template<>
struct MD5Sum< ::ros_mmaster::SrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mmaster::Srv >::value();
  }
  static const char* value(const ::ros_mmaster::SrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mmaster::SrvRequest> should match 
// service_traits::DataType< ::ros_mmaster::Srv > 
template<>
struct DataType< ::ros_mmaster::SrvRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mmaster::Srv >::value();
  }
  static const char* value(const ::ros_mmaster::SrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mmaster::SrvResponse> should match 
// service_traits::MD5Sum< ::ros_mmaster::Srv > 
template<>
struct MD5Sum< ::ros_mmaster::SrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mmaster::Srv >::value();
  }
  static const char* value(const ::ros_mmaster::SrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mmaster::SrvResponse> should match 
// service_traits::DataType< ::ros_mmaster::Srv > 
template<>
struct DataType< ::ros_mmaster::SrvResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mmaster::Srv >::value();
  }
  static const char* value(const ::ros_mmaster::SrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MMASTER_MESSAGE_SRV_H
